name: Build and Assert Assets Exists
description: Build the package and assert that file contents exist as we expect
runs:
  using: 'composite'
  steps:
    - name: Build and Assert Output
      shell: bash
      run: |-
        echo '
          target: ${{ env.dist }}
          setup:
            run: pnpm build
            cwd: ./
          expect: |
            index.js
            index.cjs
            camelcase.js
            camelcase.cjs
            jsonapi.js
            jsonapi.cjs
            standardized.js
            standardized.cjs
            types/index.d.ts
            types/index.d.cts
            types/camelcase.ts
            types/camelcase.cts
            types/jsonapi.ts
            types/jsonapi.cts
            types/standardized.ts
            types/standardized.cts


        ' >> assert-contents.config.yml
        npx assert-folder-contents
    - name: Upload dist assets to cache
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: ${{ env.dist }}
